language: objective-c
osx_image: xcode10.2
sudo: false

env:
  global:
    - WORKSPACE="XcodeGenExample.xcworkspace"
    - SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.2"
  matrix:
    - SCHEME="MyApp"
    - SCHEME="MyServices"
    - SCHEME="MyUtils"

cache:
  - cocoapods

install:
  - brew ls --versions xcodegen || brew install xcodegen
  - pod repo update
  - make project

script:
  - set -o pipefail && xcodebuild test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGNING_ALLOWED=YES | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -X llvm-cov -J "$SCHEME"
