language: objective-c
osx_image: xcode10.2
sudo: false

env:
  global:
    - WORKSPACE="XcodeGenExample.xcworkspace"
    - PROJECT="XcodeGenExample.xcodeproj"
    - SCHEME="AllTests"

cache:
  - bundler
  - cocoapods
  - directories:
    - /usr/local/Cellar/xcodegen
    - Specs

install:
  - brew link xcodegen || brew install xcodegen
  - bundle install --path vendor/bundle
  - gem install cocoacache && cocoacache restore
  - make project

script:
  - bundle exec fastlane scan
    --workspace "$WORKSPACE"
    --scheme "$SCHEME"
    --device "iPhone Xs"

after_success:
  - slather coverage
    --workspace XcodeGenExample.xcworkspace
    --scheme "$SCHEME"
    --cobertura-xml
    "$PROJECT"
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode

before_cache:
  - bundle exec save
