language: objective-c
osx_image: xcode10.2
sudo: false

env:
  global:
    - WORKSPACE="XcodeGenExample.xcworkspace"
    - SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.2"
  matrix:
    - SCHEME="MyApp"
    - SCHEME="MyServices"
    - SCHEME="MyUtils"

cache:
  - bundler
  - cocoapods
  - directories:
    - /usr/local/Cellar/xcodegen
    - Specs

install:
  - brew link xcodegen || brew install xcodegen
  - bundle update && bundle install --path vendor/bundle
  - bundle exec cocoacache restore
  - make project

script:
  - set -o pipefail && xcodebuild test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGNING_ALLOWED=YES | xcpretty -c

after_success:
  - slather coverage
    --workspace XcodeGenExample.xcworkspace
    --scheme "$SCHEME"
    --cobertura-xml
    XcodeGenExample.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode

before_cache:
  - bundle exec save
