targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: ./Sources
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
      - target: MyServices
    settings:
      PRODUCT_NAME: MyApp
      PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_NAME)
      INFOPLIST_FILE: "$(SRCROOT)/Projects/MyApp/Supporting Files/Info.plist"

  MyAppTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: MyApp

schemes:
  MyApp:
    build:
      targets:
        MyApp: all
        MyAppTests: [test]
    test:
      gatherCoverageData: true
      targets: [MyAppTests]
