targets:
  MyServices:
    templates:
      - Framework
    dependendies:
      - sdk: Combine.framework
      - target: MyUtils

  MyServicesTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: MyServices
