name: CD
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      project:
        description: "배포할 프로젝트"
        required: true
        type: choice
        options:
          - myapp
          - metabase
        default: myapp
      env:
        description: "배포할 환경 (prod, dev)"
        required: true
        default: dev
        type: choice
        options: [prod, dev]
      sha:
        description: "배포할 커밋 Full SHA"

jobs:
  build:
    strategy:
      matrix:
        project:
          - myapp
          - metabase
    runs-on: ubuntu-latest
    steps:
      - run: echo "LONG_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
        if: github.event.inputs.sha != ''

      - run: echo "LONG_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
        if: github.event.inputs.sha == ''

      - run: echo "SHORT_SHA=${LONG_SHA::7}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.LONG_SHA }}

      - name: Build
        run: echo "Building $SHORT_SHA..."; echo "Done."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "LONG_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
        if: github.event.inputs.sha != ''

      - run: echo "LONG_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
        if: github.event.inputs.sha == ''

      - run: echo "SHORT_SHA=${LONG_SHA::7}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.LONG_SHA }}

      - name: Deploy
        run: echo "Deploying $SHORT_SHA..."; echo "Done."
