name: CI

on:
  push:
    branches:
      master
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install XcodeGen
      run: brew link xcodegen || brew install xcodegen

    - name: Install Ruby Dependencies
      run: bundle install --path vendor/bundle

    - name: Generate Xcode Project
      run: make project

    - name: Run Danger
      run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

    - name: Build and Test
      run: |
        bundle exec fastlane scan \
          --workspace "Playground.xcworkspace" \
          --scheme "AllTests" \
          --device "iPhone Xs" \
          --output_style rspec \
          | grep --line-buffered -v "\[MT\]" \
          | grep --line-buffered -v "DTDeviceKit" \
          | grep --line-buffered -v "SimDevice" \
          | grep --line-buffered -v "IDETestOperationsObserverDebug" \
          | grep --line-buffered -v "iPhoneSupport" \
          | grep --line-buffered -v "/Library/Developer/Xcode/DerivedData/" \
          | egrep --line-buffered -v "\} \(\d+\.\d+"

    - name: Upload Code Coverage
      run: |
        bundle exec slather coverage \
          --workspace Playground.xcworkspace \
          --scheme "AllTests" \
          --cobertura-xml \
          "Playground.xcodeproj"
        bash <(curl -s https://codecov.io/bash) \
          -f cobertura.xml \
          -X coveragepy \
          -X gcov \
          -X xcode \
          -t 60f66a56-0399-4e79-b741-8b81f02df68f
