name: CI

on: [pull_request]

jobs:
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install XcodeGen
      run: brew link xcodegen || brew install xcodegen

    - name: Install Ruby Dependencies
      run: bundle install --path vendor/bundle

    - name: Generate Xcode Project
      run: make project

    - name: Run Danger
      run: bundle exec danger

    - name: Build and Test
      run: |
        bundle exec fastlane scan \
          --workspace "Playground.xcworkspace" \
          --scheme "AllTests" \
          --device "iPhone Xs" \
          | grep --line-buffered -v "\[MT\]"

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
